#!/usr/bin/env python
# -*- coding: utf-8 -*-
# nolo-graphite.py: send metrics from nolo plugins to graphite

import logging
import os
import sys

try:
    import ConfigParser
except ImportError:
    import configparser as ConfigParser

from nolo_graphite.nolo_metric_collector import NoloMetricCollector
from nolo_graphite.graphite_handler import GraphiteHandler


def main():
    # turn up logging if DEBUG environment variable is on
    if 'DEBUG' in os.environ:
        logging.setLevel(logging.DEBUG)

    # ensure params are sane
    if 2 > len(sys.argv):
        logging.critical("No plugin provided.")
        sys.stderr.write("usage: %s plugin\n" % sys.argv[0])
        sys.exit(-1)

    # ensure config is sane, load it
    config = ConfigParser.ConfigParser()
    config.read('/etc/nolo-graphite.conf')

    # grab plugin name from params
    plugin = sys.argv[1]

    collector = NoloMetricCollector(plugin, GraphiteHandler, config)
    collector.run()

if __name__ == '__main__':
    main()
